name: Documentation Build

on:
  workflow_dispatch:       # manual trigger
  push:
    branches: [master]

jobs:
  download-snippets:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download and extract artifacts
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\.github\scripts\download-snippets.ps1